#ifndef N_QUEENS_H
#define N_QUEENS_H
#include <gmp.h>

#define NB_QUEENS 8
#define INT_SIZE  NB_QUEENS*NB_QUEENS

// VERBOSE DIRECTIVES
#define BUILD_SHOW_COLUMNS 0
#define BUILD_SHOW_ROWS 0
#define BUILD_SHOW_DIAGONALS_1 0
#define BUILD_SHOW_DIAGONALS_2 0
#define BUILD_SHOW_SHOTS 0

#define RUN_SHOW_SOLUTIONS 0
#define RUN_SHOW_STACK_EVOLUTION 0

#endif // N_QUEENS_H
